<?php

namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Request;

class Address extends Controller
{
	//验证token获取uid
	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		checkToken();
	}
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        //
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //读取信息地址
	    $uid=$this->request->id;
	    $result=Db::table('address')->where(['uid'=>$uid,'status'=>1])->find();
//	    var_dump($result);
	    if ($result){
		    return json([
			    'code' => config('code.success'),
			    'msg' => "地址获取成功",
			    'data'=>$result,
		    ]);

	    }else{
		    return json([
			    'code' => config('code.fail'),
			    'msg' => "地址获取失败"

		    ]);
	    }
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
