<?php


namespace app\index\controller;


use think\Controller;
use think\Db;

class Cartdecnum extends Controller
{
	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		checkToken();
	}
	public function update()
	{
		$uid = $this->request->id;
		$data = $this->request->put();//获取数据
		$gid = $data['gid'];
		$sale = $data['sale'];
//		$total=$data['total'];

		$model = model('Cart');
		$cart = $model->queryone($uid);//判断购物车有无
		if ($cart) {
			Db::startTrans();//启动事务
			$cid = $cart['cid'];
			$ext = model('Cartext');

			$res=$ext->deletegoods(['gid'=>$gid,'num'=>1]);

			$Decresult = $ext->goodsnumDec(['uid' => $uid, 'gid' => $gid]);
			$numberDec = $cart->cartDec($uid, 'total');
			$priceDec = $cart->cartDec($uid, 'price', $sale);
			if ($res){
				Db::commit();//提交事务
				return json([
					'code' => config('code.success'),
					'msg' => "购物车减少成功",
					'data' => ['cid' => $cid, 'uid' => $uid]
				]);
			}



			if ($Decresult && $numberDec && $priceDec)  {
				Db::commit();//提交事务
				return json([
					'code' => config('code.success'),
					'msg' => "购物车减少成功",
					'data' => ['cid' => $cid, 'uid' => $uid]
				]);
			} else {
				Db::rollback();//事务回滚
				return json([
					'code' => config('code.fail'),
					'msg' => "购物车减少失败"

				]);
			}

		}

	}
}